apiVersion: v1
kind: ConfigMap
metadata:
  name: url-config
data:
  DB_USER: user
  DB_PASS: password
  DB_NAME_1: urlshortener1
  DB_NAME_2: urlshortener2
  DB_HOST_1: postgres-service
  DB_HOST_2: postgres-service
  DB_PORT_1: "5432"
  DB_PORT_2: "5432"
  REDIS_URL: redis-service:6379